spring.application.name=PROG3-Rattrapage


server.port=8080

kofia.datasource.url=jdbc:postgresql://localhost:5432/prg3
kofia.datasource.username=postgres
kofia.datasource.password=170308

server.error.include-message=always